# Site settings
title: Adejair Júnior
description: 'Um blog com foco no conteúdo de front-end e back-end e afins :)'
url: 'adejairjunior.com.br'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'adejairjunior'

author:
  name: 'Adejair Júnior'
  email: adejair.junioroulook@gmail.com
  twitter_username: adejairjunior1
  facebook_username:
  github_username:  Adejair
  linkedin_username:

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
